env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "l/n90Mg1knQ5jSBo3/X1KDXaKVUsEVq7TnhZY7CYYCHe8OvI30s1PtZ5TatOM87dG2I3EvxHX/O8d2X0vkNkaNo592Avvp6aM9LRkpDIQh9PTXP8q8BS/EIxgDeMJkp9pJCnE3bM0MoZfectpsQBg8v0X9uadXVeAPQiKFACNZo="

addons:
  coverity_scan:
    project:
      name: "Seldomberry/Cortex"
      description: "Build submitted via Travis CI"
    notification_email: sander.mertens8@gmail.com
    build_command_prepend: "source configure"
    build_command:   "make"
    branch_pattern: coverity_scan

script: source configure && make
